# Đái tháo đường

Bệnh 

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df= pd.read_csv('dulieuDTD.csv')

In [4]:
cols= df.columns
cols

Index(['Tuổi', 'Nghề Nghiệp', 'Trình độ', 'Tuổi thai', 'Số lần mang thai',
       'Para\nsinh – sớm – sảy – sống', 'Tiền sử đẻ con > 4kg',
       'Tiền sử GĐ mắc ĐTĐ (bố, mẹ, anh, chị em ruột) ', 'Chiều cao (m)',
       'Cân nặng trước khi mang thai (Kg)', 'Cân nặng hiện tại (Kg)',
       'Huyết áp trên', 'Huyết áp dưới',
       'Tình chất công việc về hoạt động thể lực trước khi có thai (nặng/ trung bình/ nhẹ)',
       'Tình chất công việc về hoạt động thể lực khi có thai so với trước khi có thai (nặng hơn/ bằng/ nhẹ hơn)',
       'Luyện tập thể thao trong 1 tháng gần đây: (có/ không)',
       ' Trong 1 tháng gần đây mỗi tuần luyện tập bao nhiêu ngày:  (ngày)',
       'Trung bình mỗi ngày luyện tập bao nhiêu lâu: (phút)',
       'Trước uống\n(< 5.1 mmol/l)', 'Sau 60 phút \n(< 10 mmol/l)',
       'Sau 120 phút\n(< 8.6 mmol/l)',
       'Kết luận\nBình thường: 0\nĐTĐ: 1\nNguy cơ cao: 2'],
      dtype='object')

In [5]:
Y= df[cols[-1]].values
Y= (Y!=0).astype(int)
Y

array([1, 0, 0, ..., 0, 0, 0], shape=(1280,))

In [6]:
X= []
for col in cols[:-1]:
    X.append(df[col].values.tolist())

In [7]:
X= np.array(X)
X = np.concatenate((np.ones((1, X.shape[1])), X), axis = 0)
X= X.T #chuyen vi
X.shape

(1280, 22)

In [8]:
X

array([[ 1.  , 35.  ,  2.  , ...,  4.37,  9.68,  7.52],
       [ 1.  , 39.  ,  0.  , ...,  4.05,  8.31,  7.39],
       [ 1.  , 31.  ,  3.  , ...,  4.43,  8.06,  6.75],
       ...,
       [ 1.  , 30.  , 15.  , ...,  4.52,  7.6 ,  6.42],
       [ 1.  , 24.  ,  0.  , ...,  4.48,  6.11,  5.97],
       [ 1.  , 29.  ,  0.  , ...,  4.33,  8.3 ,  7.92]], shape=(1280, 22))

In [9]:
X.shape

(1280, 22)

In [10]:
X_test= X[1000:, :]
Y_test= Y[1000:]

X= X[:1000,:]
Y= Y[:1000]

In [11]:
X.shape, X_test.shape

((1000, 22), (280, 22))

In [12]:
def sigmoid(s):
    return 1/(1 + np.exp(-s))

def logistic_sigmoid_regression(X, y, w_init, eta, tol = 1e-4, max_count = 10000):
    # X: (d,N) : N so dong, d so cot
    w = [w_init]   
    N = X.shape[1] # 1- dong
    d = X.shape[0] #0- cot
    count = 0
    check_w_after = 20 #kiem tra 20 dong de kiem tra co khac nhau khong
    while count < max_count:
        # mix data 
        mix_id = np.random.permutation(N)# permutation = trộn
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)#chạy cột và lấy dòng i = lấy 1 quan sát
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi)) #dot = nhân ma trận mxn * nxp= mxp
            w_new = w[-1] + eta*(yi - zi)*xi #w[-1] = giá trị trước đó 
            count += 1
            # stopping criteria
            if count%check_w_after == 0:                
                if np.linalg.norm(w_new - w[-check_w_after]) < tol: # k/c giữa 2 điểm đủ nhỏ 
                    return w 
            w.append(w_new)
    return w
#gọi hàm
eta = .05 
d = X.shape[1] #1 - cột
print(d)
w_init = np.random.randn(d, 1) #d - số lượng số cần lấy random, 1= giới hạn số( giá trị max)

w = logistic_sigmoid_regression(X.T, Y.T, w_init, eta) #Do định nghĩa ngược --> gọi hàm sử dụng X.T và Y.T
print(w[-1])

22
[[ -0.69603913]
 [  1.43442458]
 [ -9.82488856]
 [ -7.96414827]
 [ -1.46479484]
 [ -4.73634773]
 [ -8.17795072]
 [  2.8806575 ]
 [  1.7601741 ]
 [ -1.6519394 ]
 [ -6.6709558 ]
 [ -7.37783233]
 [-12.70874926]
 [  4.73425138]
 [ -0.78590238]
 [  2.493495  ]
 [ -2.14712054]
 [ -3.04482093]
 [ -0.59416093]
 [  6.88018379]
 [118.55580864]
 [103.82172783]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_14352\1311354770.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-s))


In [13]:
w[-1].shape

(22, 1)

In [14]:
w= w[-1]
w

array([[ -0.69603913],
       [  1.43442458],
       [ -9.82488856],
       [ -7.96414827],
       [ -1.46479484],
       [ -4.73634773],
       [ -8.17795072],
       [  2.8806575 ],
       [  1.7601741 ],
       [ -1.6519394 ],
       [ -6.6709558 ],
       [ -7.37783233],
       [-12.70874926],
       [  4.73425138],
       [ -0.78590238],
       [  2.493495  ],
       [ -2.14712054],
       [ -3.04482093],
       [ -0.59416093],
       [  6.88018379],
       [118.55580864],
       [103.82172783]])

In [15]:
Y_hat= sigmoid(np.dot(w.T, X.T))

C:\Users\Admin\AppData\Local\Temp\ipykernel_14352\1311354770.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-s))


In [16]:
Y_hat.shape

(1, 1000)

In [17]:
Y_hat

array([[1.00000000e+000, 1.00000000e+000, 2.08697962e-062,
        1.00000000e+000, 2.35697865e-137, 4.79260514e-065,
        1.00000000e+000, 1.04693451e-275, 7.88792094e-127,
        8.49487082e-070, 1.00000000e+000, 6.09733733e-027,
        7.72489637e-154, 4.32865106e-169, 1.00000000e+000,
        3.21582895e-163, 3.63098689e-086, 1.00863928e-078,
        1.53419654e-144, 2.94628856e-088, 3.90828036e-214,
        1.00000000e+000, 1.00000000e+000, 4.56169427e-053,
        6.96092361e-217, 1.00000000e+000, 1.00000000e+000,
        2.18334817e-006, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 7.67853201e-046, 3.70130662e-134,
        8.45158810e-245, 4.45689910e-138, 2.00070185e-042,
        0.00000000e+000, 1.34226694e-085, 4.38756440e-236,
        6.21577509e-063, 1.00000000e+000, 1.08868191e-293,
        3.96807450e-018, 5.84467525e-234, 1.00000000e+000,
        1.00000000e+000, 3.87176321e-185, 1.00000000e+000,
        6.17129262e-135, 0.00000000e+000, 1.00000000e+00

In [18]:
Y_= Y_hat[0] >= 0.5
Y_

array([ True,  True, False,  True, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False,  True, False, False,  True, False,  True, False,
        True, False, False, False,  True,  True, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False, False,  True,
       False, False, False,  True,  True,  True,  True,  True, False,
       False,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False,  True,  True, False, False, False,
       False, False,  True,  True, False, False,  True, False, False,
       False, False,  True,  True,  True, False,  True,  True, False,
       False,  True,

In [19]:
sum(Y_ == Y)/len(Y) #sum(Các giá trị True)/ tổng số lượng

np.float64(0.86)

In [20]:
Y_hat_test= sigmoid(np.dot(w.T, X_test.T))
Y_pred= Y_hat_test[0] >= 0.5
sum(Y_pred == Y_test)/len(Y_test) #sum(Các giá trị True)/ tổng số lượng

C:\Users\Admin\AppData\Local\Temp\ipykernel_14352\1311354770.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-s))


np.float64(0.8178571428571428)