# Đái tháo đường

Bệnh 

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df= pd.read_csv('dulieuDTD.csv')

In [4]:
cols= df.columns
cols

Index(['Tuổi', 'Nghề Nghiệp', 'Trình độ', 'Tuổi thai', 'Số lần mang thai',
       'Para\nsinh – sớm – sảy – sống', 'Tiền sử đẻ con > 4kg',
       'Tiền sử GĐ mắc ĐTĐ (bố, mẹ, anh, chị em ruột) ', 'Chiều cao (m)',
       'Cân nặng trước khi mang thai (Kg)', 'Cân nặng hiện tại (Kg)',
       'Huyết áp trên', 'Huyết áp dưới',
       'Tình chất công việc về hoạt động thể lực trước khi có thai (nặng/ trung bình/ nhẹ)',
       'Tình chất công việc về hoạt động thể lực khi có thai so với trước khi có thai (nặng hơn/ bằng/ nhẹ hơn)',
       'Luyện tập thể thao trong 1 tháng gần đây: (có/ không)',
       ' Trong 1 tháng gần đây mỗi tuần luyện tập bao nhiêu ngày:  (ngày)',
       'Trung bình mỗi ngày luyện tập bao nhiêu lâu: (phút)',
       'Trước uống\n(< 5.1 mmol/l)', 'Sau 60 phút \n(< 10 mmol/l)',
       'Sau 120 phút\n(< 8.6 mmol/l)',
       'Kết luận\nBình thường: 0\nĐTĐ: 1\nNguy cơ cao: 2'],
      dtype='object')

In [5]:
Y= df[cols[-1]].values
Y= (Y!=0).astype(int)
Y

array([1, 0, 0, ..., 0, 0, 0], shape=(1280,))

In [6]:
X= []
for col in cols[:-1]:
    X.append(df[col].values.tolist())

In [7]:
X= np.array(X)
X = np.concatenate((np.ones((1, X.shape[1])), X), axis = 0)
X= X.T #chuyen vi
X.shape

(1280, 22)

In [8]:
X

array([[ 1.  , 35.  ,  2.  , ...,  4.37,  9.68,  7.52],
       [ 1.  , 39.  ,  0.  , ...,  4.05,  8.31,  7.39],
       [ 1.  , 31.  ,  3.  , ...,  4.43,  8.06,  6.75],
       ...,
       [ 1.  , 30.  , 15.  , ...,  4.52,  7.6 ,  6.42],
       [ 1.  , 24.  ,  0.  , ...,  4.48,  6.11,  5.97],
       [ 1.  , 29.  ,  0.  , ...,  4.33,  8.3 ,  7.92]], shape=(1280, 22))

In [9]:
X.shape

(1280, 22)

In [10]:
X_test= X[1000:, :]
Y_test= Y[1000:]

X= X[:1000,:]
Y= Y[:1000]

In [11]:
X.shape, X_test.shape

((1000, 22), (280, 22))

In [12]:
def sigmoid(s):
    return 1/(1 + np.exp(-s))

def logistic_sigmoid_regression(X, y, w_init, eta, tol = 1e-4, max_count = 10000):
    # X: (d,N) : N so dong, d so cot
    w = [w_init]   
    N = X.shape[1] # 1- dong
    d = X.shape[0] #0- cot
    count = 0
    check_w_after = 20 #kiem tra 20 dong de kiem tra co khac nhau khong
    while count < max_count:
        # mix data 
        mix_id = np.random.permutation(N)# permutation = trộn
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)#chạy cột và lấy dòng i = lấy 1 quan sát
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi)) #dot = nhân ma trận mxn * nxp= mxp
            w_new = w[-1] + eta*(yi - zi)*xi #w[-1] = giá trị trước đó 
            count += 1
            # stopping criteria
            if count%check_w_after == 0:                
                if np.linalg.norm(w_new - w[-check_w_after]) < tol: # k/c giữa 2 điểm đủ nhỏ 
                    return w 
            w.append(w_new)
    return w
#gọi hàm
eta = .05 
d = X.shape[1] #1 - cột
print(d)
w_init = np.random.randn(d, 1) #d - số lượng số cần lấy random, 1= giới hạn số( giá trị max)

w = logistic_sigmoid_regression(X.T, Y.T, w_init, eta) #Do định nghĩa ngược --> gọi hàm sử dụng X.T và Y.T
print(w[-1])

22
[[-3.32692786e-02]
 [ 7.91746808e-01]
 [-1.03290680e+01]
 [-6.51706730e+00]
 [ 7.12248698e-01]
 [-2.05537919e+00]
 [-6.96826620e+00]
 [ 3.99273150e+00]
 [ 2.94320139e+00]
 [-3.84419102e+00]
 [-1.34363827e+01]
 [-6.53656492e+00]
 [-1.61822553e+01]
 [ 8.16039461e+00]
 [ 6.68309786e-01]
 [ 2.57611667e+00]
 [ 2.59190020e-01]
 [-2.29878695e+00]
 [ 8.29367055e+00]
 [ 1.14031404e+00]
 [ 1.57819599e+02]
 [ 1.39344648e+02]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_2984\1311354770.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-s))


In [13]:
w[-1].shape

(22, 1)

In [14]:
w= w[-1]
w

array([[-3.32692786e-02],
       [ 7.91746808e-01],
       [-1.03290680e+01],
       [-6.51706730e+00],
       [ 7.12248698e-01],
       [-2.05537919e+00],
       [-6.96826620e+00],
       [ 3.99273150e+00],
       [ 2.94320139e+00],
       [-3.84419102e+00],
       [-1.34363827e+01],
       [-6.53656492e+00],
       [-1.61822553e+01],
       [ 8.16039461e+00],
       [ 6.68309786e-01],
       [ 2.57611667e+00],
       [ 2.59190020e-01],
       [-2.29878695e+00],
       [ 8.29367055e+00],
       [ 1.14031404e+00],
       [ 1.57819599e+02],
       [ 1.39344648e+02]])

In [15]:
Y_hat= sigmoid(np.dot(w.T, X.T))

C:\Users\Admin\AppData\Local\Temp\ipykernel_2984\1311354770.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-s))


In [16]:
Y_hat.shape

(1, 1000)

In [17]:
Y_hat

array([[1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 6.37281141e-103, 1.00000000e+000,
        1.00000000e+000, 2.85134208e-140, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.87044619e-110, 4.32330247e-129, 1.00000000e+000,
        3.57734258e-114, 4.83452347e-016, 2.62628719e-024,
        4.37219908e-061, 1.00000000e+000, 1.03987484e-112,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        3.66794338e-187, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 3.99995424e-055,
        2.73064776e-251, 1.05035800e-090, 1.00000000e+000,
        0.00000000e+000, 2.32528955e-017, 3.17719326e-236,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 2.98967979e-228, 1.00000000e+000,
        1.00000000e+000, 2.59649286e-166, 1.00000000e+000,
        7.68299744e-020, 5.90017627e-295, 1.00000000e+00

In [18]:
Y_= Y_hat[0] >= 0.5
Y_

array([ True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False, False,  True,  True, False,  True, False,  True,
        True, False,  True, False, False,  True,  True,  True, False,
        True, False,  True, False,  True,  True, False, False, False,
        True,  True,  True, False, False, False, False,  True, False,
       False, False,  True, False,  True,  True, False, False,  True,
       False, False, False,  True,  True,  True,  True,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True, False, False, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,

In [19]:
sum(Y_ == Y)/len(Y) #sum(Các giá trị True)/ tổng số lượng

np.float64(0.698)

In [20]:
Y_hat_test= sigmoid(np.dot(w.T, X_test.T))
Y_pred= Y_hat_test[0] >= 0.5
sum(Y_pred == Y_test)/len(Y_test) #sum(Các giá trị True)/ tổng số lượng

C:\Users\Admin\AppData\Local\Temp\ipykernel_2984\1311354770.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-s))


np.float64(0.5821428571428572)

# softmax 

In [21]:
from scipy import sparse 
def convert_labels(y, C):
    """
    convert 1d label to a matrix label: each column of this 
    matrix coresponding to 1 element in y. In i-th column of Y, 
    only one non-zeros element located in the y[i]-th position, 
    and = 1 ex: y = [0, 2, 1, 0], and 3 classes then return

            [[1, 0, 0, 1],
             [0, 0, 1, 0],
             [0, 1, 0, 0]]
    """
    Y = sparse.coo_matrix((np.ones_like(y), 
        (y, np.arange(len(y)))), shape = (C, len(y))).toarray()
    return Y 

In [22]:
C = 3 #so luong nhan
Y= convert_labels(Y, C= C)

In [23]:
X= X.T

In [24]:
Y.shape

(3, 1000)

In [25]:
def softmax_stable(Z):
    """
    Compute softmax values for each sets of scores in Z.
    each column of Z is a set of score.    
    """
    e_Z = np.exp(Z - np.max(Z, axis = 0, keepdims = True))
    A = e_Z / e_Z.sum(axis = 0)
    return A

In [27]:
# cost or loss function  
def cost(X, Y, W):
    A = softmax_stable(W.T.dot(X))
    return -np.sum(Y*np.log(A))

W_init = np.random.randn(d, C)

def grad(X, Y, W):
    A = softmax_stable((W.T.dot(X)))
    E = A - Y
    return X.dot(E.T)
    
def numerical_grad(X, Y, W, cost):
    eps = 1e-6
    g = np.zeros_like(W)
    for i in range(W.shape[0]):
        for j in range(W.shape[1]):
            W_p = W.copy()
            W_n = W.copy()
            W_p[i, j] += eps 
            W_n[i, j] -= eps
            g[i,j] = (cost(X, Y, W_p) - cost(X, Y, W_n))/(2*eps)
    return g 

g1 = grad(X, Y, W_init)
g2 = numerical_grad(X, Y, W_init, cost)

print(np.linalg.norm(g1 - g2))

5.6348796481777066e-06


In [28]:
def softmax_regression(X, y, W_init, eta, tol = 1e-4, max_count = 10000):
    W = [W_init]    
    C = W_init.shape[1]
    Y = convert_labels(y, C)
    it = 0
    N = X.shape[1]
    d = X.shape[0]
    
    count = 0
    check_w_after = 20
    while count < max_count:
        # mix data 
        mix_id = np.random.permutation(N)
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)
            yi = Y[:, i].reshape(C, 1)
            ai = softmax_stable(np.dot(W[-1].T, xi))
            W_new = W[-1] + eta*xi.dot((yi - ai).T)
            print('count:',  count)
            count += 1
            # stopping criteria
            if count%check_w_after == 0:                
                if np.linalg.norm(W_new - W[-check_w_after]) < tol:
                    return W
            W.append(W_new)
    return W
eta = .05 
d = X.shape[0]
W_init = np.random.randn(d, C)

W = softmax_regression(X, Y, W_init, eta)
# W[-1] is the solution, W is all history of weights

ValueError: coordinates and data arrays must be 1-D

In [29]:
w= W[-1]

NameError: name 'W' is not defined

In [36]:
w #22 dong - 21 dac trung + 1 he so tu do #3 cot = 3 class

array([[  0.64843734,  -0.73207639,   0.62170767],
       [ -8.91608597,   9.72090025,  -2.2957898 ],
       [ 10.17659146,  -9.92499111,   0.09617171],
       [  7.03905794,  -3.61293577,   0.26474524],
       [ -3.90858519,   3.79748484,  -0.51570652],
       [  2.84261064,  -0.56577049,   1.21596128],
       [  5.80085278,  -4.77157659,  -0.09493717],
       [ -1.3803882 ,   2.66522731,  -0.21335832],
       [ -0.49661129,  -0.26490392,   0.79648603],
       [  1.78490435,  -1.80806934,   2.67324004],
       [ 10.26415525,  -6.91632599,  -3.3797912 ],
       [ 10.48229558,  -6.77949562,  -2.66102595],
       [ 10.44020125,  -6.98770944,  -3.96648031],
       [  1.56312904,   1.58121621,  -2.76769362],
       [  1.46091225,  -0.68561366,   1.41282065],
       [ -1.98381175,   1.62444048,  -0.91505903],
       [  0.7668469 ,  -0.49807783,  -0.7314765 ],
       [  1.02544892,  -1.53947421,   0.38415073],
       [ -0.98586319,   1.17285859,  -0.41860578],
       [ -7.09898376,   8.37840

In [37]:
w.shape

(22, 3)

In [38]:
def pred(W, X):
    """
    predict output of each columns of X
    Class of each x_i is determined by location of max probability
    Note that class are indexed by [0, 1, 2, ...., C-1]
    """
    A = softmax_stable(W.T.dot(X))
    return np.argmax(A, axis = 0)

In [41]:
Z = pred(W[-1], X_test.T)

In [42]:
Z

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

In [43]:
np.sum(Z==Y_test)/len(Y_test)

0.7964285714285714